#
# application.yml — главный конфигурационный файл Spring Boot.
#
#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.xml
    enabled: true

jwt:
  secret: 6L+Z5piv5LiN5Liq5Lq655qE5a+G56CB5LiN6KaB5rGC5L2P5ZCO5Y+w5LiN5Y+v5Lul
  expiration: 86400000
  header: Authorization
  prefix: Bearer

encryption:
  key: my_very_secure_secret_key_that_is_long_enough_32_chars

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging:
  level:
    com.example.bankcards: DEBUG
    org.springframework.security: DEBUG
